// put our endpoints
@endpoint = https://dnmjksx4o9.execute-api.eu-central-1.amazonaws.com/prod/

//GET request
GET {{endpoint}}/hello/
###

POST {{endpoint}}/spaces/
Content-Type: : application/json

{
    "location": "Nepal",
    "name": "Best location"
}
###
